u1 = User.create(first_name: "FirstName1", last_name: "LastName1",email: "email1@email.com", password: "1", password_confirmation: "1", is_admin: '0')
Payment.create(amount: "10.01", amount_date: "01.01.2000", description: "1 pay", user_id: u1.id )
Payment.create(amount: "20.02", amount_date: "02.02.2000", description: "2 pay", user_id: u1.id )
Payment.create(amount: "30.03", amount_date: "04.03.2000", description: "3 pay", user_id: u1.id )
u2 = User.create(first_name: "FirstName2", last_name: "LastName2",email: "email2@email.com", password: "2", password_confirmation: "2", is_admin: '0')
u3 = User.create(first_name: "FirstName3", last_name: "LastName3",email: "email3@email.com", password: "3", password_confirmation: "3", is_admin: '1')
